/*
Authenticating with Spotify.
Fetching user playlists.
Parsing and formatting playlist data for further processing.
*/
// import SpotifyWebApi from 'spotify-web-api-node';
import axios from 'axios';
// import dotenv from 'dotenv';
// dotenv.config();

const clientId = import.meta.env.VITE_SPOTIFY_CLIENT_ID;
// const clientSecret = import.meta.env.VITE_SPOTIFY_CLIENT_SECRET;
const redirectUri = 'http://localhost:5173/auth-popup';
// /auth-popup

// const spotifyApi = new SpotifyWebApi({
//   clientId: import.meta.env.VITE_SPOTIFY_CLIENT_ID,
//   clientSecret: import.meta.env.VITE_SPOTIFY_CLIENT_SECRET,
//   redirectUri: 'http://localhost:5173/',
// });

export function authPopup() {
  //   const state = 'ElevatorBabyBoyMusicFunTimes5!';
  const scope = 'playlist-modify-public';
  //   const userAuthUrl = spotifyApi.createAuthorizeURL(scopes, state);
  const userAuthUrl =
    `https://accounts.spotify.com/authorize?` +
    `client_id=${clientId}&response_type=token&redirect_uri=${encodeURIComponent(redirectUri)}` +
    `&scope=${encodeURIComponent(scope)}&show_dialog=true`;

  const popup = window.open(
    userAuthUrl,
    'SpotifyAuth',
    'width=700, height=700'
  );

  if (!popup) {
    console.error('Popup window blocked!');
  }
  console.log('Message received:', event.data);
  // Listen for auth popup
  const handleMessage = (event: MessageEvent) => {
    if (event.origin !== window.location.origin) return;
    if (event.data.spotify_access_token) {
      console.log(event.data.spotify_access_token);
      localStorage.setItem(
        'spotify_access_token',
        event.data.spotify_access_token
      );
      // Ensure that app recognize the user is now logged in
      window.location.reload();
    }
  };
  window.addEventListener('message', handleMessage, false);
}

export async function generatePlaylist(
  accessToken: string,
  songs: Array<{ spotifyId: string }>
): Promise<string | null> {
  try {
    const userResponse = await axios.get('https://api.spotify.com/v1/me', {
      headers: { Authorization: `Bearer ${accessToken}` },
    });
    const userId = userResponse.data.id;

    // Create the playlist
    const response = await axios.post(
      `https://api.spotify.com/v1/users/${userId}/playlists`,
      {
        name: 'Vibe Check Playlist',
        public: true,
        description: 'Generated by Vibe Check App',
      },
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
        },
      }
    );

    const playlistId = response.data.id;
    console.log('Playlist created:', playlistId);

    // Add songs to playlist  
    if (songs.length > 0) {
      const trackUris = songs.map((song) => `spotify:track:${song.spotifyId}`);
      await axios.post(
        `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
        {
          uris: trackUris,
        },
        {
          headers: {
            Authorization: `Bearer ${accessToken}`,
            'Content-Type': 'application/json',
          },
        }
      );
      console.log('Added songs to playlist:', trackUris.length);
    }

    return playlistId;
  } catch (error) {
    console.error('Error creating playlist:', error);
    return null;
  }
}
